# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    database_service:
      class: AppBundle\Services\DatabaseService
      arguments: ['%database_host%', '%database_user%', '%database_password%', '%database_name%', '@logger']
    entity_manager:
      class: AppBundle\Services\EntityManager
      arguments: ['@database_service', '@logger']
